apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image: 082554297530.dkr.ecr.us-east-1.amazonaws.com/danproject113:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
          - secretRef:
              name: passworkscrect
          - configMapRef:
              name: danproject
        env:
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: danproject
                key: DB_USER 
      restartPolicy: Always
